name: Run Linter

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to checkout for linter'
        type: string
        required: false
  workflow_call:
    inputs:
      tag:
        description: 'Tag to checkout for linter'
        type: string
        required: false

jobs:
  laravel-pint:
    name: Run Pint - Laravel Linter
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Checkout code at ${{ inputs.tag }}
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag || '' }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute Pint
        run: vendor/bin/pint --test
